@extends('layouts.app')

@section('title')
    Benefits of Joining Kingdom Challenge
    @endsection

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-9">
                <p align="left"><span style="font-family: Ubuntu;"><span style="color: #ff0000;"><span style="font-size: x-large;"><strong>Fourteen Benefits Of Joining Kingdom Challenge</strong></span></span></span><a name="_GoBack"></a></p>
                <p align="left"><span style="font-family: Ubuntu;"><span style="font-size: small;"><span style="color: #ff0000;"><span style="font-size: xx-large;">T</span></span><span style="font-size: medium;">he Genesis of </span><span style="font-size: medium;"><strong>Kingdom Challenge</strong></span><span style="font-size: medium;"> began by fixating on one question: </span><span style="color: #008000;"><span style="font-size: large;"><strong>What Does It Take To Drive Radical Results&mdash;Fast?</strong></span></span> <span style="font-size: medium;">This comes from my background that I started everything in life a little too late and I wanted to catch up with age and the world as well as build and leave Legacies that can outlive </span><span style="color: #ff6600;"><span style="font-size: medium;"><strong>Seven Generations</strong></span></span><span style="font-size: medium;"> after I die! That it what made me to create and establish </span><span style="color: #ff0000;"><span style="font-size: medium;"><strong>115 Business Companies And Organisations</strong></span></span><span style="font-size: medium;"> at my 52</span><sup><span style="font-size: medium;">nd</span></sup><span style="font-size: medium;"> birthday!</span></span></span></p>
                <p align="left"><span style="font-family: Ubuntu;">When I solved that puzzle and put all of the pieces together, I knew if people followed it, that they would indeed be able to produce radical results&mdash;fast! So I&rsquo;m now looking for people who are crazy enough to stick with me on this challenge for all 100 days.</span></p>
                <p align="left"><span style="font-family: Ubuntu;"><strong>Now it&rsquo;s your turn to make the impossible possible!</strong></span></p>
                <p align="left"><span style="font-family: Ubuntu;"><strong>Is the Kingdom Challenge hard?</strong> Does it require discipline, accountability, hard work, sustained commitment and relentless action?</span></p>
                <p align="left"><span style="font-family: Ubuntu;"><strong>You bet it does, but the results are ridiculously huge and life changing!</strong></span></p>
                <h2 class="western" align="left"><span style="font-family: Ubuntu;"><span style="color: #ff0000;"><span style="font-size: medium;">What Do You Get With The Kingdom Challenge?</span></span> <span style="font-size: medium;">The benefits of participating in the Kingdom Challenge are numerous. You get everything you need for transforming your life...for crushing your goals ...getting in great shape... becoming debt free...skyrocketing your sales and income, and achieving ANY goal you want in record time. When you dare and join Kingdom Challenge, you will get the following fourteen outstanding empowerment items:</span></span></h2>
                <h2 class="western" align="left"><span style="font-family: Ubuntu;"><span style="color: #ff0000;"><span style="font-size: medium;">100 Hard-core Notes and Video Challenge Lessons:</span></span> <span style="font-size: medium;">The Kingdom Challenge does not mess around. These lessons are direct, intense and actionable...because if you want extreme results...you've got to go to the extreme.</span><span style="font-size: medium;"><br /> </span></span><br /> <span style="font-family: Ubuntu;"><span style="color: #ff0000;"><span style="font-size: medium;">100 Hard-core Mp3 (Audio) Challenge Lessons:</span></span> <span style="font-size: medium;">We want you taking action and winning all day long...and we want you to have easy 24/7 access to reinforce the challenge lesson while you drive, walk, jog or bike.<br /> </span></span><br /> <span style="font-family: Ubuntu;"><span style="color: #ff0000;"><span style="font-size: medium;">Massive Action Plan:</span></span> <span style="font-size: medium;">With this daily implementation plan, we&rsquo;ve done all the &ldquo;heavy lifting&rdquo; for you. It includes 100 implementation strategies for getting maximum gain with minimum effort.<br /> </span></span><br /> <span style="font-family: Ubuntu;"><span style="color: #ff0000;"><span style="font-size: medium;">Crash Course on Goal Setting:</span></span> <span style="font-size: medium;">Forget everything you know about goal setting. This crash course is like getting an MBA on what it takes to inspire excellence and drive radical results&mdash;fast.<br /> </span></span><br /> <span style="font-family: Ubuntu;"><span style="color: #ff0000;"><span style="font-size: medium;">Daily Reminders:</span></span> <span style="font-size: medium;">An aesthetically beautiful email will greet you each day for the next 100 days. It will lead you to your new lesson and strategy for crushing your goals.<br /> </span></span><br /> <span style="font-family: Ubuntu;"><span style="color: #ff0000;"><span style="font-size: medium;">Daily Goal And Progress Journal:</span></span> <span style="font-size: medium;">Each day requires a game plan, deadlines and accountability. This daily discipline will keep you focused, on track and progressively moving forward.</span></span></h2>
                <h2 class="western" align="left"><span style="font-family: Ubuntu;"><span style="color: #ff0000;"><span style="font-size: medium;">Community Forum:</span></span> <span style="font-size: medium;">Inspire and be inspired by high-performers from all over the world. You'll connect with other members, create friendships and enjoy rich conversations.<br /> </span></span><br /> <span style="font-family: Ubuntu;"><span style="color: #ff0000;"><span style="font-size: medium;">Private Membership Site:</span></span> <span style="font-size: medium;">Once you get your credentials...you'll immediately have access to a private hangout for high achievers who are making big things happen in the world.<br /> </span></span><br /> <span style="font-family: Ubuntu;"><span style="color: #ff0000;"><span style="font-size: medium;">Goal Setting Forms:</span></span> <span style="font-size: medium;">Your life changes the moment you set and commit to a big challenging goal. These forms will help you navigate your way to a bigger, bolder future.<br /> </span></span><br /> <span style="font-family: Ubuntu;"><span style="color: #ff0000;"><span style="font-size: medium;">Force Multipliers:</span></span> <span style="font-size: medium;">Most people spend their lives playing addition...but Kingdom Challenge is a game of multiplication. You'll learn proven strategies for making large performance gains.<br /> </span></span><br /> <span style="font-family: Ubuntu;"><span style="color: #ff0000;"><span style="font-size: medium;">After Action Reviews (Aar):</span></span> <span style="font-size: medium;">AAR&lsquo;s are weekly measurement tools aimed squarely at driving a persistent improvement in skill, knowledge, accountability and overall results.<br /> </span></span><br /> <span style="font-family: Ubuntu;"><span style="color: #ff0000;"><span style="font-size: medium;">Live Weekly Training Call:</span></span> <span style="font-size: medium;">Free access to a weekly training call led by your Coach Julius Peter Oyet. You'll get motivation, coaching and new insights on what it takes to live a large and successful life.<br /> </span></span><br /> <span style="font-family: Ubuntu;"><span style="color: #ff0000;"><span style="font-size: medium;">Screen Savers &amp; Inspirational Wallpaper:</span></span> <span style="font-size: medium;">Make your phone, desktop and tablet come to life with these Kingdom Challenge 100 stunning images and motivational messages...all designed to get your mojo working.</span><span style="font-size: medium;"><br /> </span></span><br /> <span style="font-family: Ubuntu;"><span style="color: #ff0000;"><span style="font-size: medium;">Integrity Pledge:</span></span> <span style="font-size: medium;">The Kingdom Challenge is more than just driving results...it's also about demonstrating wisdom, excellence, character, integrity, and every noble virtue and best practice.</span></span></h2>
                <p align="left"><span style="font-family: Ubuntu;"><span style="font-size: small;"><span style="font-size: medium;">I believe that if you are going to work hard to achieve a goal, then you owe it to yourself to find the fastest way to get it done. The Kingdom Challenge </span><span style="font-size: medium;"><strong>IS</strong></span><span style="font-size: medium;"> the fastest way.</span></span></span></p>
                <p align="left">Until we talk again, keep growing strong, big and never forget; Wisdom Is The Principle Thing!</p>
                <p align="left">&nbsp;</p>
            </div>
            <div class="col-md-3">
                <nav class="clearfix guest">
                    <ul>
                        <li><a href="{{ url('/') }}">Home</a></li>
                        <li><a href="{{ url('auth/register') }}">Register</a></li>
                        <li><a href="{{ url('auth/login') }}">Login</a></li>
                    </ul>
                </nav>

                <div><h3>Quick Links</h3></div>
                <ol>
                    <li><a href="{{ url('about') }}">About the Kingdom Challenge</a></li>
                    <li><a href="{{ url('benefits-of-joining-kingdom-challenge') }}">Fourteen Benefits Of Joining Kingdom Challenge</a></li>
                    <li><a href="{{ url('consquencies') }}">The Consquences of Not being Challenged</a></li>
                    <li><a href="{{ url('seven-reasons-for-loving-kingdom-challenge') }}">The Top 7 Reasons Why People Love The Kingdom Challenge</a></li>
                    <li><a href="{{ url('ten-benefits-of-a-challenge') }}">Ten benefits of a challenge</a></li>
                    <li><a href="{{ url('now-are-you-ready') }}">Now are you ready for a challenge?</a></li>
                    <li><a href="{{ url('auth/register') }}">Register now</a></li>
                </ol>
            </div>
        </div>
    </div>
    @include('partials.footer')
    @endsection