@extends('layouts.app')

@section('title')
    Commitment to excellence
    @endsection

@section('content')
    <div class="container">
        <p style="text-align: left;" align="left"><strong><span style="color: #ff0000;"><span style="font-family: Times, serif;"><span style="font-size: xx-large;"><span lang="en-GB">Commitment to Excellence</span></span></span></span></strong></p>
        <p style="text-align: left;" align="left"><strong><span style="color: #ff0000;"><span style="font-family: Times, serif;"><span style="font-size: 300%;"><span lang="en-GB"><strong>T</strong></span></span></span></span></strong><strong><span style="color: #ff0000;"><span style="font-family: Times, serif;"><span style="font-size: medium;"><span lang="en-GB"><strong>he Pursuit of Excellence</strong></span></span></span></span></strong><span style="color: #333333;"><span style="font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;"><span style="font-size: small;">&nbsp;</span></span></span><span style="color: #333333;"><span style="font-family: Times, serif;"><span style="font-size: medium;"><span lang="en-GB">is not only politically correct, it&rsquo;s also highly profitable. Excellence is a form of currency&mdash;reputational currency. A commitment to excellence can help you capture true wealth and realize the inherent value of your potential, while a lack of commitment devalues potential, credibility, and reputation.</span></span></span></span></p>
        <p style="text-align: left;"><strong><span style="color: #333333;"><span style="font-family: Times, serif;"><span style="font-size: medium;"><span lang="en-GB"><strong>Each of us must determine the specific achievements we must accomplish in order to deem our own life &ldquo;excellent.&rdquo;</strong></span></span></span></span></strong><span style="color: #333333;"><span style="font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;"><span style="font-size: small;">&nbsp;</span></span></span><span style="color: #333333;"><span style="font-family: Times, serif;"><span style="font-size: medium;"><span lang="en-GB">Your responsibilities in doing this include choosing a career path, deciding what to and what not to believe in, what to learn and apply in life, and what actions to take. You can help yourself with these responsibilities by consistently asking one simple question:&nbsp;</span></span></span></span><strong><span style="color: #333333;"><span style="font-family: Times, serif;"><span style="font-size: medium;"><span lang="en-GB"><strong>How are your thoughts and actions reflective of a life committed to excellence?</strong></span></span></span></span></strong></p>
        <p lang="en-GB" style="text-align: left;"><span style="color: #333333;"><span style="font-family: Times, serif;"><span style="font-size: medium;">So what exactly is excellence? Think of it as the process of continually growing and improving yourself and your life. Excellence includes achievement of goals that can be measured by constantly asking the question;</span></span></span></p>
        <p style="text-align: left;"><span style="color: #333333;">&ldquo;</span><strong><span style="color: #333333;"><span style="font-family: Times, serif;"><span style="font-size: small;"><span lang="en-GB"><strong>Is what I&rsquo;m doing truly reflective of a life committed to excellence?&rdquo;</strong></span></span></span></span></strong></p>
        <p lang="en-GB" style="text-align: left;"><span style="color: #333333;"><span style="font-family: Times, serif;"><span style="font-size: medium;">Your greatest responsibility in seeking excellence is to define what this means precisely in your life, then to choose the best course of action to make it happen.</span></span></span></p>
        <p style="text-align: left;"><span style="color: #333333;"><span style="font-family: Times, serif;"><span style="font-size: medium;"><span lang="en-GB">Excellence is not a relative term;&nbsp;</span></span></span></span><strong><span style="color: #ff0000;"><span style="font-family: Times, serif;"><span style="font-size: medium;"><span lang="en-GB"><strong>It Is The Standard By Which You Must Judge What You Do.</strong></span></span></span></span></strong><span style="color: #333333;"><span style="font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;"><span style="font-size: small;">&nbsp;</span></span></span><span style="color: #333333;"><span style="font-family: Times, serif;"><span style="font-size: medium;"><span lang="en-GB">You will quickly discover that committing yourself to a life of excellence cannot be accomplished haphazardly.</span></span></span></span></p>
        <p style="text-align: left;"><span style="color: #333333;"><span style="font-family: Times, serif;"><span style="font-size: medium;"><span lang="en-GB">Excellence never occurs by accident. It always comes as the result of quality thinking and purposeful execution. To become the person you were meant to be, everything you do must be done with&nbsp;</span></span></span></span><strong><span style="color: #333333;"><span style="font-family: Times, serif;"><span style="font-size: medium;"><span lang="en-GB"><strong>the single purpose of achieving excellence.</strong></span></span></span></span></strong><span style="color: #333333;"><span style="font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;"><span style="font-size: small;">&nbsp;</span></span></span><span style="color: #333333;"><span style="font-family: Times, serif;"><span style="font-size: medium;"><span lang="en-GB">You must do it with the unshakeable belief and understanding that excellence counts.</span></span></span></span></p>
        <p style="text-align: left;"><span style="color: #333333;"><span style="font-family: Times, serif;"><span style="font-size: medium;"><span lang="en-GB">You must live and die in the spirit of quality and excellence. The measurement of your &ldquo;best&rdquo; begins and ends with the marks of excellence&mdash;nothing less. Some people perpetually create their own dissatisfaction by consistently slipping into mediocrity. This can easily be fixed, too, right now by simply deciding to&nbsp;</span></span></span></span><strong><span style="color: #333333;"><span style="font-family: Times, serif;"><span style="font-size: medium;"><span lang="en-GB"><strong>quit doing less than excellent work.</strong></span></span></span></span></strong><span style="color: #333333;"><span style="font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;"><span style="font-size: small;">&nbsp;</span></span></span><span style="color: #333333;"><span style="font-family: Times, serif;"><span style="font-size: medium;"><span lang="en-GB">What a profound idea!</span></span></span></span></p>
        <p lang="en-GB" style="text-align: left;"><span style="color: #333333;"><span style="font-family: Times, serif;"><span style="font-size: medium;">Mediocrity is a choice; it&rsquo;s not always made consciously, but it is still a choice. You commit career malpractice every time you do things in a mediocre manner; every time you show up late; every time you are unprepared.</span></span></span></p>
        <p style="text-align: left;"><strong><span style="color: #ff0000;"><span style="font-family: Times, serif;"><span style="font-size: medium;"><span lang="en-GB"><strong>There is no inherent value in mediocrity</strong></span></span></span></span></strong><strong><span style="color: #333333;"><span style="font-family: Times, serif;"><span style="font-size: medium;"><span lang="en-GB"><strong>,</strong></span></span></span></span></strong><span style="color: #333333;"><span style="font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;"><span style="font-size: small;">&nbsp;</span></span></span><span style="color: #333333;"><span style="font-family: Times, serif;"><span style="font-size: medium;"><span lang="en-GB">so there is no reason for people to stop and pay attention to you or your work. Choose never to compromise your talent, quality, and high standards, and you will never choose mediocrity.</span></span></span></span></p>
        <p style="text-align: left;"><span style="color: #333333;"><span style="font-family: Times, serif;"><span style="font-size: medium;"><span lang="en-GB">Being world-class has nothing to do with size, education, or bloodline;&nbsp;</span></span></span></span><strong><span style="color: #333333;"><span style="font-family: Times, serif;"><span style="font-size: medium;"><span lang="en-GB"><strong>it has everything to do with decision, commitment, action, and persistence.</strong></span></span></span></span></strong></p>
        <p lang="en-GB" style="text-align: left;"><span style="color: #333333;"><span style="font-family: Times, serif;"><span style="font-size: medium;">Excellence is a destination for anyone who appreciates, respects, and demonstrates hard work and good judgment. But excellence is not something that you attain and then put in a trophy case. It is a habit&mdash;a momentary happening&mdash;a crossroad where the body, mind, and spirit all work together. Those who have legitimately reached the summit of their careers, relationships, gamesmanship, have worked harder and longer; studied and planned more assiduously; practiced more self-denial; and overcome more difficulties than those who have not risen as far.</span></span></span></p>
        <p style="text-align: left;"><strong><span style="color: #333333;"><span style="font-family: Times, serif;"><span style="font-size: medium;"><span lang="en-GB"><strong>You can become excellent in a second&mdash;beginning right now.</strong></span></span></span></span></strong><span style="color: #333333;"><span style="font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;"><span style="font-size: small;">&nbsp;</span></span></span><span style="color: #333333;"><span style="font-family: Times, serif;"><span style="font-size: medium;"><span lang="en-GB">Start by visualizing yourself as the best teacher, artist, manager, coach, or parent that you aspire to become&mdash;and start acting the part.</span></span></span></span></p>
        <p lang="en-GB" style="text-align: left;"><span style="color: #333333;"><span style="font-family: Times, serif;"><span style="font-size: medium;">Put yourself in the best possible position to succeed, and then perform your script exactly as it plays out in your mind. It takes less than a second to raise your standards higher than they are right now.</span></span></span></p>
        <p style="text-align: left;"><strong><span style="color: #333333;"><span style="font-family: Times, serif;"><span style="font-size: medium;"><span lang="en-GB"><strong>You must merely decide to deliver world-class quality, but it takes a lifetime of passionate pursuit to maintain it,</strong></span></span></span></span></strong><span style="color: #333333;"><span style="font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;"><span style="font-size: small;">&nbsp;</span></span></span><span style="color: #333333;"><span style="font-family: Times, serif;"><span style="font-size: medium;"><span lang="en-GB">whether you are the concierge at a hotel, the manager of a small department, or the CEO of an international fi rm. One of the wonderful things about excellence is that when it is on, you&rsquo;ll know it because you&rsquo;ll enjoy the experience through all five senses:</span></span></span></span></p>
        <p style="text-align: left;"><strong><span style="color: #333333;"><span style="font-family: Times, serif;"><span style="font-size: medium;"><span lang="en-GB"><strong>Look:</strong></span></span></span></span></strong><span style="color: #333333;"><span style="font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;"><span style="font-size: small;">&nbsp;</span></span></span><span style="color: #333333;"><span style="font-family: Times, serif;"><span style="font-size: medium;"><span lang="en-GB">Impeccable grooming, solid posture, and complete preparation for a business meeting display the look of excellence.</span></span></span></span></p>
        <p style="text-align: left;"><strong><span style="color: #333333;"><span style="font-family: Times, serif;"><span style="font-size: medium;"><span lang="en-GB"><strong>Feel:</strong></span></span></span></span></strong><span style="color: #333333;"><span style="font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;"><span style="font-size: small;">&nbsp;</span></span></span><span style="color: #333333;"><span style="font-family: Times, serif;"><span style="font-size: medium;"><span lang="en-GB">An inviting smile, the fine leather of a new car, and the smooth texture of fabric demonstrate the feel of excellence and quality.</span></span></span></span></p>
        <p style="text-align: left;"><strong><span style="color: #333333;"><span style="font-family: Times, serif;"><span style="font-size: medium;"><span lang="en-GB"><strong>Sound:</strong></span></span></span></span></strong><span style="color: #333333;"><span style="font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;"><span style="font-size: small;">&nbsp;</span></span></span><span style="color: #333333;"><span style="font-family: Times, serif;"><span style="font-size: medium;"><span lang="en-GB">A rich singing voice, an expansive vocabulary, and the friendliness of a wake-up call are examples of excellence in communication.</span></span></span></span></p>
        <p style="text-align: left;"><strong><span style="color: #333333;"><span style="font-family: Times, serif;"><span style="font-size: medium;"><span lang="en-GB"><strong>Taste:</strong></span></span></span></span></strong><span style="color: #333333;"><span style="font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;"><span style="font-size: small;">&nbsp;</span></span></span><span style="color: #333333;"><span style="font-family: Times, serif;"><span style="font-size: medium;"><span lang="en-GB">The design of a home, the font of a letter, and the sweetness of a chef&rsquo;s dessert all celebrate excellence in taste.</span></span></span></span></p>
        <p style="text-align: left;"><strong><span style="color: #333333;"><span style="font-family: Times, serif;"><span style="font-size: medium;"><span lang="en-GB"><strong>Smell:</strong></span></span></span></span></strong><span style="color: #333333;"><span style="font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;"><span style="font-size: small;">&nbsp;</span></span></span><span style="color: #333333;"><span style="font-family: Times, serif;"><span style="font-size: medium;"><span lang="en-GB">The aroma of fresh flowers, the bouquet of a perfume, and the scent from freshly baked cookies help us to experience the smell of excellence.</span></span></span></span></p>
        <p style="text-align: left;"><span style="color: #333333;"><span style="font-family: Times, serif;"><span style="font-size: medium;"><span lang="en-GB">Excellence wastes little time in making its presence felt as it represents an example of truly great thinking.&nbsp;</span></span></span></span><strong><span style="color: #333333;"><span style="font-family: Times, serif;"><span style="font-size: medium;"><span lang="en-GB"><strong>We should all appreciate the merits of rich thoughts, high personal standards, and a commitment to squeeze every ounce of ones potential.</strong></span></span></span></span></strong></p>
        <p lang="en-GB" style="text-align: left;"><span style="color: #333333;"><span style="font-family: Times, serif;"><span style="font-size: medium;">Excellence begins as a decision&mdash;one where you look at your life, business, and relationships and ask, &ldquo;What do I see that needs improvement? What do I wish I didn&rsquo;t see? What would I ideally like to see? What do I hear other people say about me? What do I see that rubs me the wrong way about others?&rdquo;</span></span></span></p>
        <p lang="en-GB" style="text-align: left;"><span style="color: #333333;"><span style="font-family: Times, serif;"><span style="font-size: medium;">The answer to these questions, along with others like them, will provide the points of improvement you seek.</span></span></span></p>
        <p style="text-align: left;"><strong><span style="color: #333333;"><span style="font-family: Times, serif;"><span style="font-size: medium;"><span lang="en-GB"><strong>Implementing and sustaining a drive toward excellence will put you in the best position relative to others for opportunity.</strong></span></span></span></span></strong><span style="color: #333333;"><span style="font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;"><span style="font-size: small;">&nbsp;</span></span></span><span style="color: #333333;"><span style="font-family: Times, serif;"><span style="font-size: medium;"><span lang="en-GB">It will also help you build support because you demonstrate real accountability, genuine results, and superior performance.</span></span></span></span></p>
        <p style="text-align: left;" align="center"><strong><span style="color: #ff0000;"><span style="font-family: Times, serif;"><span style="font-size: x-large;"><span lang="en-GB"><strong>Seven Guiding Principles Of Excellence</strong></span></span></span></span></strong></p>
        <p lang="en-GB" style="text-align: left;"><span style="color: #333333;"><span style="font-family: Times, serif;"><span style="font-size: medium;">The following are the Seven Guiding Principles of Excellence. They serve as the building blocks in starting and sustaining the construction of your ideal future, and serve as guideposts for success throughout the Kingdom Challenge.</span></span></span></p>
        <p lang="en-GB" style="text-align: left;"><span style="color: #333333;"><span style="font-family: Times, serif;"><span style="font-size: medium;">You must always live a virtuous life. It is not enough to just live; you must live with nobility and honour.</span></span></span></p>
        <p lang="en-GB" style="text-align: left;"><span style="color: #333333;"><span style="font-family: Times, serif;"><span style="font-size: medium;">You must always act to inspire, promote, and celebrate excellence in yourself and in others.</span></span></span></p>
        <p lang="en-GB" style="text-align: left;"><span style="color: #333333;"><span style="font-family: Times, serif;"><span style="font-size: medium;">You must always choose your actions based on good reasons and good reasoning, not out of fear, self-interest, or other short-term considerations that compromise long-term opportunities.</span></span></span></p>
        <p style="text-align: left;"><span style="color: #333333;">&nbsp;</span><strong><span style="color: #333333;"><span style="font-family: Times, serif;"><span style="font-size: medium;"><span lang="en-GB"><strong>You must always seek out the truth and live with it, even if that truth is unpopular or uncomfortable</strong></span></span></span></span></strong><span style="color: #333333;"><span style="font-family: Times, serif;"><span style="font-size: medium;"><span lang="en-GB">.</span></span></span></span></p>
        <p style="text-align: left;"><span style="color: #333333;">&nbsp;<span style="font-family: Times, serif;"><span style="font-size: medium;"><span lang="en-GB">You must always rely on principles that stand the test of time and changes in circumstances. The conclusions you draw from them must be ones to which you can be constantly faithful.</span></span></span></span></p>
        <p style="text-align: left;"><span style="color: #333333;">&nbsp;<span style="font-family: Times, serif;"><span style="font-size: medium;"><span lang="en-GB">You must always do the right thing and never do wrong willingly, even when others have wronged you.</span></span></span></span></p>
        <p style="text-align: left;"><span style="color: #333333;">&nbsp;<span style="font-family: Times, serif;"><span style="font-size: medium;"><span lang="en-GB">You must always keep your promises and honour your commitments, provided that they are just.</span></span></span></span></p>
        <p lang="en-GB" style="text-align: left;"><span style="color: #333333;"><span style="font-family: Times, serif;"><span style="font-size: medium;">By mastering one principle, one day at a time, you will build a stairway to higher and higher attainment. Your stairway will be strong because you have concentrated on one thing at a time.</span></span></span></p>
        <p style="text-align: left;"><strong><span style="color: #333333;"><span style="font-family: Times, serif;"><span style="font-size: medium;"><span lang="en-GB"><strong>Excellence is a guilty pleasure,</strong></span></span></span></span></strong><span style="color: #333333;"><span style="font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;"><span style="font-size: small;">&nbsp;</span></span></span><span style="color: #333333;"><span style="font-family: Times, serif;"><span style="font-size: medium;"><span lang="en-GB">as it creates confidence and enhances peace of mind. It functions as an insurance policy against mediocrity and an assurance of continuous growth. A genuine commitment to excellence allows you to bump yourself up from coach to first class anytime you wish.</span></span></span></span></p>
        <p style="text-align: left;"><span style="color: #333333;"><span style="font-family: Times, serif;"><span style="font-size: medium;"><span lang="en-GB">We all have a range of career choices and opportunities,&nbsp;</span></span></span></span><strong><span style="color: #333333;"><span style="font-family: Times, serif;"><span style="font-size: medium;"><span lang="en-GB"><strong>but we expand this range and quality of our choices when we practice excellence.</strong></span></span></span></span></strong><span style="color: #333333;"><span style="font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;"><span style="font-size: small;">&nbsp;</span></span></span><span style="color: #333333;"><span style="font-family: Times, serif;"><span style="font-size: medium;"><span lang="en-GB">Adversely, we blackball ourselves from future opportunities when we do mediocre work.</span></span></span></span></p>
        <p style="text-align: left;"><strong><span style="color: #333333;"><span style="font-family: Times, serif;"><span style="font-size: small;"><span lang="en-GB"><strong>Most people are not hard acts to follow, and that&rsquo;s exactly why a commitment to excellence is the ultimate competitive advantage.</strong></span></span></span></span></strong></p>
        <p lang="en-GB" style="text-align: left;"><span style="color: #333333;"><span style="font-family: Times, serif;"><span style="font-size: medium;">Excellence is achieved via qualitative, not quantitative, shifts in developing skills. Be part of a qualitatively different world or environment, where excellence is expected and practice is a key to achieving excellence.</span></span></span></p>
        <p style="text-align: left;"><strong><span style="color: #333333;"><span style="font-family: Times, serif;"><span style="font-size: medium;"><span lang="en-GB"><strong>Never relax the rules of excellence.</strong></span></span></span></span></strong><span style="color: #333333;"><span style="font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;"><span style="font-size: small;">&nbsp;</span></span></span><span style="color: #333333;"><span style="font-family: Times, serif;"><span style="font-size: medium;"><span lang="en-GB">When you compromise quality, you suffer physical and emotional detachment from your goals. Have the belief that the efficiencies of your business and life are infinite, that everything can be improved upon, that every project can be completed in an excellent fashion.</span></span></span></span></p>
        <p style="text-align: left;"><span style="color: #333333;"><span style="font-family: 'Arial Narrow', serif;"><span style="font-size: small;">Until we talk again, keep growing strong, big and never forget; Wisdom Is The Principle Thing!</span></span></span></p>
        <p style="text-align: left;"><span style="color: #333333;">&nbsp;</span></p>
        <p style="text-align: left;" align="left"><br /> </p>
    </div>

    @include('partials.footer')
    @endsection