@extends('layouts.app')

@section('content')
    <div class="container">
        <p align="center"><span style="font-size: x-large;"><strong>The True Cost of Freedom</strong></span></p>
        <p align="center"><a name="_GoBack"></a> <span style="font-family: Times, serif;"><span style="font-size: small;"><span style="font-family: 'Arial Narrow', serif;"><span style="font-size: small;"><strong>By Your Coach: Julius Peter Oyet</strong></span></span></span></span></p>
        <p align="justify"><span style="font-family: Times, serif;"><span style="font-size: small;"><span style="font-family: 'Arial Narrow', serif;"><span style="font-size: small;">Like most everything in life&hellip;</span></span><strong><span style="font-family: 'Arial Narrow', serif;"><span style="font-size: small;">freedom is a choice and with choice comes responsibility.</span></span></strong><span style="font-family: 'Arial Narrow', serif;"><span style="font-size: small;"> In my many years of coaching and consulting, I&rsquo;ve found that, in virtually every case, the decision to take on a challenge, to confront fear and to achieve important goals comes down to the desire for greater freedom in one&rsquo;s life. While many have difficulty putting it into words&hellip;</span></span><em><span style="font-family: 'Arial Narrow', serif;"><span style="font-size: small;">I assure you, the opportunity to enjoy and continually expand one&rsquo;s personal freedom is what distinguishes high and low achievers.</span></span></em></span></span></p>
        <p align="justify"><span style="font-family: Times, serif;"><span style="font-size: small;"><span style="font-family: 'Arial Narrow', serif;"><span style="font-size: small;"><strong>Freedom Isn&rsquo;t Free:</strong></span></span><span style="font-family: 'Arial Narrow', serif;"><span style="font-size: small;"> Regardless of how you choose to define freedom, it is ONLY secured through the pain and inconvenience of suffering&hellip; </span></span><strong><span style="font-family: 'Arial Narrow', serif;"><span style="font-size: small;">And once secured, it MUST be diligently protected at all costs.</span></span></strong><span style="font-family: 'Arial Narrow', serif;"><span style="font-size: small;"> We all were born into a culture that took generations to create. The people who came before us secured many of the freedoms you and I enjoy at the cost of great suffering and sacrifice.</span></span></span></span></p>
        <p align="justify"><span style="font-family: Times, serif;"><span style="font-size: small;"><span style="font-family: 'Arial Narrow', serif;"><span style="font-size: small;">Freedom, along with every goal you want to achieve, and every dream you want to manifest comes with a price tag. There is no such thing as a FREE LUNCH when it comes to enjoying greater freedom and fulfilment. To enjoy freedom and to achieve any goal,&nbsp;</span></span><strong><span style="font-family: 'Arial Narrow', serif;"><span style="font-size: small;">You Must Choose The Suffering</span></span></strong><span style="font-family: 'Arial Narrow', serif;"><span style="font-size: small;">&nbsp;that&rsquo;s right for you, you must accept that reality, you must embrace that truth, and then you must live with it every day of your life. Unfortunately most people do not want to hear nor accept this truth, and I suppose that&rsquo;s why the truth tends to be treated as a pinata. Something people prefer to smack around.</span></span></span></span></p>
        <p align="justify"><span style="font-family: Times, serif;"><span style="font-size: small;"><span style="font-family: 'Arial Narrow', serif;"><span style="font-size: small;">HOWEVER&hellip; The moment you choose not to continue to pay the price of freedom and success is the precise moment you choose to suffer the consequences of failure and regret which is the worst kind of suffering. </span></span><strong><span style="font-family: 'Arial Narrow', serif;"><span style="font-size: small;">And&hellip;completely unnecessary.</span></span></strong><span style="font-family: 'Arial Narrow', serif;"><span style="font-size: small;"> Be mindful, the suffering cost of failure is ALWAYS&nbsp;HIGHER than the suffering price you must pay for freedom and success.</span></span></span></span></p>
        <p align="justify"><span style="font-family: Times, serif;"><span style="font-size: small;"><span style="font-family: 'Arial Narrow', serif;"><span style="font-size: small;"><strong>The following are examples of the suffering costs of failure:</strong></span></span></span></span></p>
        <p align="justify"><span style="font-family: Times, serif;"><span style="font-size: small;"><span style="font-family: 'Arial Narrow', serif;"><span style="font-size: small;">If you lack financial discipline, you will suffer the painful consequences of debt, poor credit and sleepless nights.</span></span></span></span></p>
        <p align="justify"><span style="font-family: Times, serif;"><span style="font-size: small;"><span style="font-family: 'Arial Narrow', serif;"><span style="font-size: small;">If you do not manage your diet, you will suffer the painful cost of diabetes, poor fitting clothing and low self-esteem.</span></span></span></span></p>
        <p align="justify"><span style="font-family: Times, serif;"><span style="font-size: small;"><span style="font-family: 'Arial Narrow', serif;"><span style="font-size: small;">If you do not keep your promises, you will suffer the painful loss of reputation, contaminated character and live your life being known as someone with an integrity deficit.</span></span></span></span></p>
        <p align="justify"><span style="font-family: Times, serif;"><span style="font-size: small;"><strong><span style="font-family: 'Arial Narrow', serif;"><span style="font-size: small;">Sooner or later, each of us must come to the understanding that neither freedom nor success is free and that we either willingly choose to pay the price of success or by default, pay the cost of failure.</span></span></strong><span style="font-family: 'Arial Narrow', serif;"><span style="font-size: small;"> WILL YOU&hellip;or WON&rsquo;T YOU? I have come to know intimately that the price of success is often more than people are willing to pay, but not more than they are capable of paying.</span></span></span></span></p>
        <p align="justify"><span style="font-family: Times, serif;"><span style="font-size: small;"><span style="font-family: 'Arial Narrow', serif;"><span style="font-size: small;"><strong>The following are examples of the suffering costs of freedom and success:</strong></span></span></span></span></p>
        <p align="justify"><span style="font-family: Times, serif;"><span style="font-size: small;"><span style="font-family: 'Arial Narrow', serif;"><span style="font-size: small;">If you suffer the costs of disciplined spending and investing habits you enjoy peace of mind, early retirement, and most importantly&hellip;FINANCIAL FREEDOM.</span></span></span></span></p>
        <p align="justify"><span style="font-family: Times, serif;"><span style="font-size: small;"><span style="font-family: 'Arial Narrow', serif;"><span style="font-size: small;">If you suffer the costs of daily exercise and nutrition you get to enjoy a great physique, an exceptional quality of life, and&hellip;</span></span><span style="font-family: 'Arial Narrow', serif;"><span style="font-size: small;"><strong>Physical Freedom</strong></span></span><span style="font-family: 'Arial Narrow', serif;"><span style="font-size: small;">.</span></span></span></span></p>
        <p align="justify"><span style="font-family: Times, serif;"><span style="font-size: small;"><span style="font-family: 'Arial Narrow', serif;"><span style="font-size: small;">If you suffer the cost of excellence, keeping your promises and honoring your commitments, you will experience a stellar reputation, enhanced social capital and expanded career opportunities.</span></span></span></span></p>
        <p align="justify"><span style="font-family: Times, serif;"><span style="font-size: small;"><span style="font-family: 'Arial Narrow', serif;"><span style="font-size: small;">This allows you to the enjoy a future filled with virtually unlimited PERSONAL FREEDOMS. Ultimately freedom is the result of maturity and personal mastery. It derives from the rigorous, ongoing deployment of noble virtues to include: discipline, accountability, commitment, perseverance, ingenuity, and good old-fashioned hard-work to name just a few. </span></span><strong><span style="font-family: 'Arial Narrow', serif;"><span style="font-size: small;">The greatest gift you can give yourself is the gift of freedom as with it, you have the wonderful opportunity to do something big, bold and beautiful with your life, and ultimately leave behind a legacy that&rsquo;s much bigger than you.</span></span></strong></span></span></p>
        <p align="justify"><span style="font-family: Times, serif;"><span style="font-size: small;"><span style="font-family: 'Arial Narrow', serif;"><span style="font-size: small;">I created Kingdom Challenge to provide you with a series of tools and strategies to achieve any goal fast, but even more important I designed this program so that it is the vehicle by which you can enjoy the gift of freedom.</span></span></span></span></p>
        <p align="justify"><span style="font-family: 'Arial Narrow', serif;">Until We Talk Again, </span><span style="font-family: 'Arial Narrow', serif;"><em><strong>Just Remember, You Are </strong></em></span><span style="color: #008000;"><span style="font-family: 'Arial Narrow', serif;"><em><strong>Absolutely Extraordinary!</strong></em></span></span> <span style="font-family: 'Arial Narrow', serif;">You Are An </span><span style="color: #0000ff;"><span style="font-family: 'Arial Narrow', serif;"><strong>Incredible Warehouse Of Success</strong></span></span><span style="color: #0000ff;"><span style="font-family: 'Arial Narrow', serif;">,</span></span><span style="font-family: 'Arial Narrow', serif;"> Keep Growing Strong, Big, Bold And Never Forget </span><span style="color: #ff6600;"><span style="font-family: 'Arial Narrow', serif;"><strong>To Inspire, Promote And Celebrate Success!</strong></span></span></p>
    </div>

    @include('partials.footer')
@endsection