@extends('layouts.app')

@section('content')
<div class="container">
    <p class="western" lang="en-US" align="center"><span style="color: #ff0000;"><span style="font-size: x-large;"><strong>The Ten Rules Of The Kingdom Challenge</strong></span></span></p>
    <p class="western" lang="en-US" align="justify"><span style="color: #ff6600;"><span style="font-size: xx-large;">L</span></span>ife is, in some respects, like a game of chess. The opening gambit may have been made long ago and responses long set in motion. Indeed, some pieces may have been lost, but the board is still filled with opportunity. Every move has importance. Every decision has consequence. Every wasted opportunity is a tactical error. Every move counts!</p>
    <p class="western" lang="en-US" align="justify">Different and sometimes conflicting interests drive the competition on the other side of the chessboard of life. You are often your own greatest adversary, prone to self-destruction, sabotage, and other means of moving away from victory and into checkmate.</p>
    <p lang="en-US"><strong>So how do we do it? How do we rise to meet a challenge? Here&rsquo;s your playbook for success&hellip;</strong></p>
    <p class="western" lang="en-US" align="justify"><span id="Frame1" dir="ltr"></span>Just as chess has its rules so does the game of life, and while knowing game&rsquo;s rule does not guarantee that you&rsquo;ll win every match, disregarding the rules makes playing the game difficult &ndash; and winning virtually impossible.</p>
    <p class="western" lang="en-US" align="justify"><span style="color: #ff0000;"><strong>Rule #1: Throw Your Hat in the Ring: </strong></span>The best act of creation is self-creation, and while life does thrust challenges upon us, the best challenges in life are the ones we create for ourselves. Actively look for opportunities to stretch yourself physically, emotionally, intellectually, spiritually, vocationally, artistically, musically, any way that tests your mettle.</p>
    <p class="western" lang="en-US" align="justify"><span style="color: #ff0000;"><strong>Rule #2: Believe It Will Be So: </strong></span>The world takes us at our own valuation. It believes in the person who believes in themselves, but it has little use for the timid soul, the one who is never certain, who cannot rely on his own judgment, who operates from a position of fear. Victory begins in the mind, so begin by believing it will be so.</p>
    <p class="western" lang="en-US" align="justify"><span style="color: #ff0000;"><strong>Rule #3: Enforce Your Will: </strong></span>Every great achievement and comeback in history has been the result of the choices, the determinations, and the creations of the human will. It is impossible to look a challenge in the eye without perceiving how much victory depends upon the extent to which your will is cultivated, strengthened, and enforced.</p>
    <p class="western" lang="en-US" align="justify"><span style="color: #ff0000;"><strong>Rule #4: Do What Needs to Be Done: </strong></span>The ability to make yourself do WHAT needs to be done, WHEN it must be done, whether you like it or not, is what you need to meet the demands of a challenge. Most people are able but unwilling to master this rule.</p>
    <p class="western" lang="en-US" align="justify"><span style="color: #ff0000;"><strong>Rule #5: Persevere Until the End: </strong></span>Perseverance is ultimately a physical, emotional, and spiritual demonstration of how badly you want to succeed. It&rsquo;s fueled by a heart-pouncing, ego-bashing, soul-searching test of your limits. So let them see you sweat. You express your greatness not by the acts you perform, but by the perseverance that made those acts possible.</p>
    <p class="western" lang="en-US" align="justify"><span style="color: #ff0000;"><strong>Rule #6: No Excuses: </strong></span>If you&rsquo;re up to the demands of a challenging goal, you&rsquo;ll find a way. If not, you&rsquo;ll find an excuse. And if you experiment with excuses, it&rsquo;s largely because you find your talents to be inadequate. Excuses are personality defects, a symptom of mediocrity, and a character stain in need of removal.</p>
    <p class="western" lang="en-US" align="justify"><span style="color: #ff0000;"><strong>Rule #7: Push Yourself: </strong></span>Competing at the highest level is the greatest test of one&rsquo;s character, ability, and spirit. Don&rsquo;t limit your challenges; challenge your limits. Push and demand more from yourself, because if the goal doesn&rsquo;t challenge you, it cannot change you. Sometimes it&rsquo;s a good thing to bite off more than you can chew.</p>
    <p class="western" lang="en-US" align="justify"><span style="color: #ff0000;"><strong>Rule #8: Raise the Stakes: </strong></span>Rising up to meet the demands of a challenge requires you to raise the bar of your performance as well as the stakes of accountability. There is no greater challenge than to have someone relying upon you to deliver on your word, and no greater satisfaction than to vindicate their expectation.</p>
    <p class="western" lang="en-US" align="justify"><span style="color: #ff0000;"><strong>Rule #9: Take Intelligent Risks: </strong></span>No mountains can be climbed, no hearts won, no opportunities seized, no books written, no elections won, and no victories enjoyed without risk. Risk-taking is not an opportunity to be avoided, but to be exploited, as long as you do it intelligently.</p>
    <p class="western" lang="en-US" align="justify"><span style="color: #ff0000;"><strong>Rule #10: Celebrate: </strong></span>To pay the price, to work long and hard, to compete fairly at the peak of your abilities until the goal is achieved, are all part of the sweetness of rising to meet any challenge. Celebrating is a joyful, beautiful, and selfish act of kindness that allows you to reflect on and reinforce the many acts of courage, commitment, and risk-taking involved in securing victory. It reminds you of what you have become, what you have overcome, and what you are capable of doing.</p>
    <p class="western" lang="en-US" align="justify"><span style="font-family: 'Arial Narrow', serif;">Until we talk again, keep growing strong, big and never forget; Wisdom Is The Principle Thing!</span></p>
    <p class="western" lang="en-US">&nbsp;</p>
</div>


@endsection