@extends('layouts.app')

@section('tittle')
    Benefits of a challenge
    @endsection

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-9">
                <p class="western" align="left"><span style="font-family: Ubuntu;"><span style="color: #ff0000;"><span style="font-size: xx-large;"><strong>The Ten Benefits of Taking on a Challenge</strong></span></span></span></p>
                <p class="western" align="left"><span style="color: #ff0000;"><strong>A Challenge Develops Mental Toughness</strong></span><span style="color: #ff0000;">: </span>It&rsquo;s actually pretty simple. You either rise to meet the mental demands and physical rigors of a challenge, or you succumb to them. And because victory begins in the mind, all challenges are initially won or lost between your ears.</p>
                <p class="western" align="left">The very nature of a challenge sets an appropriate stage for practicing mental toughness, which by definition means a psychological edge that enables one to remain focused and confident during high-pressure situations to perform at one&rsquo;s full potential. <em><strong>Mental toughness means bending the body&rsquo;s software to control its hardware</strong></em>. It works if you&rsquo;re standing behind the ball on a match-deciding penalty kick. It works if you&rsquo;re presenting to a roomful of people. It works, if you&rsquo;re sitting that final exam.</p>
                <p class="western" align="left"><span style="color: #ff0000;"><strong>A Challenge Stands Down Fear: </strong></span>A challenge is unique in that it immediately engages the fight-or-flight mechanism, and you never know how you are going to react until you are faced with it.</p>
                <p class="western" align="left"><strong>Fear Is Never A Reason For Quitting</strong>. It&rsquo;s only an excuse for those unwilling to face their doubts, insecurities, and mental monster. Therefore, your first duty in rising to meet a challenge is to conquer fear and the mental resistance it brings along with it. Get rid of it quickly, or get steamrolled by it. If you&rsquo;re ever going to find your greatness, you must decide that what you want is BIGGER and more important than the fear which prevents you from achieving it.</p>
                <p class="western" align="left"><span style="color: #ff0000;"><strong>A Challenge Inspires Courageous Acts: </strong></span>What good is a challenge or a big, ambitious goal if there is no willingness to overcome fear, mental and physical resistance, adversity, or self-doubt? The conceptual opposite of courage is cowardice. We are therefore confronted with the reality that we either habitually practice courage, or we habitually practice cowardice. Courage is remarkable in that it takes on the form of every virtue at the testing point. When courage is tested, it manifests itself in the form of character, initiative, self-control, and responsible behavior. When cowardice is tested, it presents itself in opposite forms to include bad character, procrastination, excuses, and blame.</p>
                <p class="western" align="left"><span style="color: #ff0000;"><strong>A Challenge Tests Your Limits: </strong></span>When you rise to meet a challenge, you will never be the same again. You either cope or crumble. You become better or bitter. You emerge stronger or weaker. It has to be this way<span style="color: #ff0000;">, as a challenge exists to tests your limits, to push you beyond the breaking point, and to separate you from the herd. </span>You&rsquo;ll never know the full measure of your potential until you are tested. You can never be sure whether you&rsquo;ll step up or falter in any given situation. Passing the tests presented by a challenging goal proves that you are tougher, more resilient, and far more capable than you ever imagined.</p>
                <p class="western" align="left"><span style="color: #ff0000;"><strong>A Challenge Focuses Attention: </strong></span>A great challenge is like a great romance. It calls for your passion and your devotion and it demands to be the center of your attention. Rising to meet a challenge is a form of seduction. It means concentrating your energy and resources on what&rsquo;s most important: <strong>Ke</strong>eping the blue fire burning! You do that by making everything count. Everything you think, say, and do must be focused on goal acquisition and on leveraging all available resources. Focus is best seen as a preemptive strike against mediocrity. The moment you focus on a challenging goal, your goal becomes a magnet that pulls you and your resources toward it. The more focused your energies, the more power you generate, and the sooner you will live happily ever after.</p>
                <p class="western" align="left"><span style="color: #ff0000;"><strong>A Challenge Builds Self-Confidence: </strong></span>Think of a challenge &ndash; any kind of challenging goal. Ask yourself, what role does self-confidence play in rising to meet that challenge? The fact is that no mountains can be climbed, no hearts won, no opportunities seized, no books written, no elections won, and no victories enjoyed without self-confidence. Now think of something you fear &ndash; anything that makes you flinch. Ask yourself, what role does self-confidence play in overcoming fear? Fear is the greatest enemy you will ever face. It impedes your ability to succeed physically, emotional, spiritually, and financially. Fear negatively impacts everything you do, and have. <span style="color: #17365d;">The inspired ability to rise to a challenge and climb great heights is directly attributable to your self-confidence. As your challenges build, so does your self-confidence.</span></p>
                <p class="western" align="left"><span style="color: #ff0000;"><strong>A Challenge Matures Perspective: </strong></span>Few things in life are capable of radically altering your perspective, but developing the capacity to rise to a challenge not only impacts the size of your results; it transforms your mind and expands your worldview. It changes everything. A challenge involves psychological trauma that induces fear, self-doubt and insecurity, while simultaneously dislodging you from your comfort zone, ultimately bringing about a superior performance. By rising to meet a challenge, you provide yourself with undeniable proof that you have what it takes.</p>
                <p class="western" align="left"><span style="color: #ff0000;"><strong>A Challenge Demands Superior Execution: </strong></span>A challenge has limited value if not overcome, and expecting to get better results from the same old behavior will only succeed in perpetuating your current situation. It will NOT get you to another level of performance. Great companies, lives, and families are built around extraordinary execution skills. The better you execute, the better you perform and the bigger the challenges you can take on. It&rsquo;s that simple. You must become acutely aware that a challenge has razor-thin margins for error and will not tolerate lapses in judgment or sloppy execution. It calls for profound self-discipline and demands that you execute as if your life and reputation depend on the outcome.</p>
                <p class="western" align="left"><span style="color: #ff0000;"><strong>A Challenge Calls For An Indomitable Spirit: </strong></span>It is irresponsible to take on a big challenge without the will, heart, and mindset to win it, as nothing can withstand the power of an indomitable spirit. In your efforts to rise to meet a challenge, you will be buffeted and pummeled. You will be criticized and opposed. You will be attacked and assaulted. You will struggle and fall. Your commitment will be relentlessly tested, and that is precisely why a challenge calls for an indomitable, unconquerable spirit. Having an indomitable spirit means that you have the type of spirit incapable of being overcome, subdued, or vanquished. If you passionately believe that you are up to the challenge and committed to seeing it through to the end, it is your right and responsibility to cultivate an unbeatable mind and enforce your will over the world.</p>
                <p align="left"><span style="font-family: Ubuntu;"><span style="color: #ff0000;"><strong>A Challenge Empowers Freedom</strong></span><span style="color: #ff0000;">: </span>Freedom isn&rsquo;t free. It requires blood, sweat, and tears. But freedom is the ultimate prize for rising to meet the rigorous demands of a challenge. In virtually every case, the decision to rise to meet a challenge boils down to the desire for greater freedom in one&rsquo;s life. This includes freedoms from and freedoms to;</span></p>
                <p class="western" align="left">To enjoy these freedoms requires that you rise to the challenges life presents and pay the required price in full, in advance, and without complaint.</p>
                <p class="western" align="left">Until we talk again, keep growing strong, big and never forget; Wisdom Is The Principle Thing!</p>
                <p class="western" align="left">&nbsp;</p>
            </div>
            <div class="col-md-3">
                <nav class="clearfix guest">
                    <ul>
                        <li><a href="{{ url('/') }}">Home</a></li>
                        <li><a href="{{ url('auth/register') }}">Register</a></li>
                        <li><a href="{{ url('auth/login') }}">Login</a></li>
                    </ul>
                </nav>

                <div><h3>Quick Links</h3></div>
                <ol>
                    <li><a href="{{ url('about') }}">About the Kingdom Challenge</a></li>
                    <li><a href="{{ url('benefits-of-joining-kingdom-challenge') }}">Fourteen Benefits Of Joining Kingdom Challenge</a></li>
                    <li><a href="{{ url('consquencies') }}">The Consquences of Not being Challenged</a></li>
                    <li><a href="{{ url('seven-reasons-for-loving-kingdom-challenge') }}">The Top 7 Reasons Why People Love The Kingdom Challenge</a></li>
                    <li><a href="{{ url('ten-benefits-of-a-challenge') }}">Ten benefits of a challenge</a></li>
                    <li><a href="{{ url('now-are-you-ready') }}">Now are you ready for a challenge?</a></li>
                    <li><a href="{{ url('auth/register') }}">Register now</a></li>
                </ol>
            </div>
        </div>
    </div>
    @include('partials.footer')
    @endsection