@extends('layouts.app')

@section('content')
    <div class="container">
        <p class="western" lang="en-GB" align="left"><span style="color: #ff6600;"><span style="font-family: 'Arial Narrow', serif;"><span style="font-size: x-large;"><strong>Welcome To Kingdom Challenge</strong></span></span></span></p>
        <p class="western" lang="en-GB" align="left"><span style="font-family: 'Arial Narrow', serif;">Our Mission is &ldquo;To </span><span style="color: #ff0000;"><span style="font-family: 'Arial Narrow', serif;"><span style="font-size: x-large;"><strong>Inspire</strong></span></span></span><span style="font-family: 'Arial Narrow', serif;"><strong>, </strong></span><span style="color: #008000;"><span style="font-family: 'Arial Narrow', serif;"><span style="font-size: x-large;"><strong>Promote</strong></span></span></span><span style="font-family: 'Arial Narrow', serif;"> and </span><span style="color: #800000;"><span style="font-family: 'Arial Narrow', serif;"><span style="font-size: x-large;"><strong>Celebrate</strong></span></span></span> <span style="color: #3366ff;"><span style="font-family: 'Arial Narrow', serif;"><span style="font-size: x-large;"><strong>Wisdom</strong></span></span></span><span style="font-family: 'Arial Narrow', serif;">&rdquo;</span></p>
        <p class="western" lang="en-GB" align="left"><span style="font-family: 'Arial Narrow', serif;">The </span><span style="font-family: 'Arial Narrow', serif;"><strong>Kingdom Challenge</strong></span> <span style="font-family: 'Arial Narrow', serif;">is your catalyst for dramatically accelerating your results and overall performance to allow you maximise your </span><span style="color: #ff0000;"><span style="font-family: 'Arial Narrow', serif;"><span style="font-size: x-large;"><strong>Full Potentials</strong></span></span></span><span style="font-family: 'Arial Narrow', serif;"> and achievement within </span><span style="font-family: 'Arial Narrow', serif;"><strong>100 Days</strong></span> <span style="font-family: 'Arial Narrow', serif;">more than others can do in 10 years!</span></p>
        <h4 class="western" lang="en-GB" align="left"><span style="color: #ff0000;"><span style="font-family: 'Arial Narrow', serif;"><span style="font-size: large;">Here's the Plan and How It Works</span></span></span></h4>
        <p lang="en-GB" align="left"><span style="font-family: Times, serif;"><span style="font-size: small;"><span style="font-family: 'Arial Narrow', serif;"><span style="font-size: medium;">For the next 100 days...you&rsquo;ll need to do </span></span><strong><span style="font-family: 'Arial Narrow', serif;"><span style="font-size: medium;">just 3 things.</span></span></strong></span></span></p>
        <p lang="en-GB" align="left"><span style="font-family: Times, serif;"><span style="font-size: small;"><strong><span style="font-family: 'Arial Narrow', serif;"><span style="font-size: medium;">1. Identify Five Challenging Goals</span></span></strong><span style="font-family: 'Arial Narrow', serif;"><span style="font-size: medium;">: These are the ones that call out to you, &ldquo;Come and get me&rdquo;. You must set edgy and mind blowing goals because if your goals don't challenge you, they will not change you. So consider this an invitation to </span></span><strong><span style="font-family: 'Arial Narrow', serif;"><span style="font-size: medium;">Think Bigger,</span></span></strong><span style="font-family: 'Arial Narrow', serif;"><span style="font-size: medium;"> as you'll be competing at the highest level to ensure maximum performance gains.</span></span></span></span></p>
        <p lang="en-GB" align="left"><span style="font-family: Times, serif;"><span style="font-size: small;"><strong><span style="font-family: 'Arial Narrow', serif;"><span style="font-size: medium;">2. Follow Your Kingdom Challenge for 100 days.</span></span></strong><span style="font-family: 'Arial Narrow', serif;"><span style="font-size: medium;"> You'll receive a new challenge lesson every day&mdash;for the next 100 days from the day of starting. Every challenge lesson is designed to move you </span></span><strong><span style="font-family: 'Arial Narrow', serif;"><span style="font-size: medium;">DEMONSTRABLY</span></span></strong><span style="font-family: 'Arial Narrow', serif;"><span style="font-size: medium;"> closer to the transformational results you desire in 100 days by using the Principle of Compounded Effort.</span></span></span></span></p>
        <p lang="en-GB" align="left"><span style="font-family: Times, serif;"><span style="font-size: small;"><strong><span style="font-family: 'Arial Narrow', serif;"><span style="font-size: medium;">3. Say Bye to Your Comfort Zone.</span></span></strong><span style="font-family: 'Arial Narrow', serif;"><span style="font-size: medium;"> You'll be pushed, harassed and harangued for the next 100 days as from the moment you begin...fears will be confronted, the bar will be raised higher, expectations will be through the roof, deadlines and accountability will be ruthlessly enforced...and </span></span><strong><span style="font-family: 'Arial Narrow', serif;"><span style="font-size: medium;">each day, your goal will be to beat yesterday.</span></span></strong></span></span></p>
        <h4 class="western" lang="en-GB" align="left"><span style="color: #ff0000;"><span style="font-family: 'Arial Narrow', serif;"><span style="font-size: large;">Do Those Things and You'll Get These Things</span></span></span></h4>
        <ol style="list-style-type: lower-roman;">
            <li class="western" lang="en-GB"><span style="font-family: 'Arial Narrow', serif;">You'll make more progress in 100 days than most people have over the course of ten years.</span><span style="font-family: 'Arial Narrow', serif;"><span style="font-size: small;"><br /> </span></span></li>
            <li class="western" lang="en-GB"><span style="font-family: 'Arial Narrow', serif;">You'll learn a proven system for </span><strong><span style="font-family: 'Arial Narrow', serif;">driving radical results</span></strong><span style="font-family: 'Arial Narrow', serif;"> that you can use the rest of your life.<br /> </span></li>
            <li class="western" lang="en-GB"><span style="font-family: 'Arial Narrow', serif;">You'll develop an indomitable, relentless, unstoppable spirit that is extremely inspiring.<br /> </span></li>
            <li class="western" lang="en-GB"><span style="font-family: 'Arial Narrow', serif;">You'll build </span><strong><span style="font-family: 'Arial Narrow', serif;">supreme self-confidence</span></strong><span style="font-family: 'Arial Narrow', serif;"> as your ability to rise to the mental demands and physical rigours of the Kingdom Challenge strengthens your core.<br /> </span></li>
            <li class="western" lang="en-GB"><span style="font-family: 'Arial Narrow', serif;">You'll find out what you are really capable of...</span><strong><span style="font-family: 'Arial Narrow', serif;">GREATNESS</span></strong><span style="font-family: 'Arial Narrow', serif;">.</span></li>
        </ol>
        <h3 class="western" lang="en-GB" align="left"><span style="color: #ff0000;"><span style="font-family: 'Arial Narrow', serif;">Boldly declare today that: Yes, I Want To Achieve My Goals Faster!</span></span></h3>
        <p class="western" lang="en-GB" align="left">Until we talk again, keep growing strong, big and never forget; Wisdom Is The Principle Thing!</p>
        <p class="western" lang="en-GB" align="left">&nbsp;</p>
    </div>

    @include('partials.footer')

@endsection